export { InitData } from './init-data.interface';
export { Season } from './season.interface';
export { GameOperation } from './game-operation.interface';
export { TableEntry } from './table-entry.interface';
export { TablePointCorrections } from './table-entry.interface';
export { ScorerEntry } from './scorer-entry.interface';
export { GameScheduleEntry } from './game-schedule-entry.interface';
export { Game } from './game.interface';
export { GameResult } from './game.interface';
export { GamePlayers } from './game.interface';
export { GamePlayerEntry } from './game.interface';
export { GameEvent } from './game.interface';
export { League } from './league.interface';
export { LeagueClass } from './league-class.interface';
export { Association } from './association.interface';
export * from './user.interface';
export * from './user-notification.interface';
export * from './league.interface';
export * from './normalized-event.interface';
export * from './league-with-operation.interface';
export * from './team.interface';
export * from './club.interface';
