import { OverlayModule } from '@angular/cdk/overlay';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { NgModule } from '@angular/core';
import { RouterModule } from '@angular/router';
import {
  AwardTitlePipe,
  CompletedAwardsFilterPipe,
  HasStartingPlayerPipe,
  StartingPlayerPositionTitlePipe,
} from 'src/app/_helpers/_pipes';
import * as Atoms from './components/atoms';
import * as Molecules from './components/molecules';
import * as Organisms from './components/organisms';
import * as Pipes from './pipes';
import * as HelperPipes from 'src/app/_helpers/_pipes';

@NgModule({
  imports: [CommonModule, RouterModule, OverlayModule, FormsModule],
  declarations: [
    Atoms.LogoComponent,
    Atoms.TabItemComponent,
    Atoms.ButtonComponent,
    Atoms.WhistleIconComponent,
    Molecules.MatchDayComponent,
    Molecules.OperationComponent,
    Molecules.PaginationComponent,
    Molecules.RefereeAutocompleteComponent,
    Organisms.ConfirmationDialogComponent,
    Organisms.ConfirmationComponent,
    Organisms.LeagueNavigationComponent,
    Organisms.SidebarComponent,
    Organisms.NotificationComponent,
    Organisms.MetanavigationComponent,
    Organisms.FavoritesNavigationComponent,
    Organisms.HeaderComponent,
    Organisms.SimilarLeaguesComponent,
    Pipes.GradientPipe,
    Pipes.NormalizeEventPipe,
    Pipes.NormalizeMatchResultPipe,
    Pipes.NormalizeRefereePipe,
    Pipes.NormalizeLeagueRoutePipe,
    Pipes.RouteMergePipe,
    Pipes.ToNumberPipe,
    Pipes.FilterPeriodEventsPipe,
    Pipes.ReverseEventsPipe,
    Pipes.SumFieldPipe,
    Organisms.MobileHeaderComponent,
    HelperPipes.AdditionalClubFilterPipe,
    HelperPipes.AwardTitlePipe,
    HelperPipes.ClubPlayerLicensePipe,
    HelperPipes.CompletedAwardsFilterPipe,
    HelperPipes.CurrentPeriodPipe,
    HelperPipes.GameNoticeHeadlinePipe,
    HelperPipes.GameNoticeVisibilityPipe,
    HelperPipes.GameTimelineFilterPipe,
    HelperPipes.GroupIdentifierFilterPipe,
    HelperPipes.HasStartingPlayerPipe,
    HelperPipes.PeriodFilterPipe,
    HelperPipes.ReversePeriodsPipe,
    HelperPipes.SortPlayersPipe,
    HelperPipes.SortTrikotnumbersPipe,
    HelperPipes.StartingPlayerPositionTitlePipe,
    HelperPipes.TeamLineupPlayerPipe,
  ],
  exports: [
    Atoms.LogoComponent,
    Atoms.TabItemComponent,
    Atoms.ButtonComponent,
    Atoms.WhistleIconComponent,
    Molecules.MatchDayComponent,
    Molecules.OperationComponent,
    Molecules.PaginationComponent,
    Molecules.RefereeAutocompleteComponent,
    Organisms.ConfirmationDialogComponent,
    Organisms.ConfirmationComponent,
    Organisms.LeagueNavigationComponent,
    Organisms.SidebarComponent,
    Organisms.NotificationComponent,
    Organisms.MetanavigationComponent,
    Organisms.FavoritesNavigationComponent,
    Organisms.HeaderComponent,
    Organisms.SimilarLeaguesComponent,
    Pipes.GradientPipe,
    Pipes.NormalizeEventPipe,
    Pipes.NormalizeMatchResultPipe,
    Pipes.NormalizeRefereePipe,
    Pipes.NormalizeLeagueRoutePipe,
    Pipes.RouteMergePipe,
    Pipes.ToNumberPipe,
    Pipes.FilterPeriodEventsPipe,
    Pipes.ReverseEventsPipe,
    Pipes.SumFieldPipe,
    Organisms.MobileHeaderComponent,
    HelperPipes.AdditionalClubFilterPipe,
    HelperPipes.ClubPlayerLicensePipe,
    HelperPipes.CurrentPeriodPipe,
    HelperPipes.GameNoticeHeadlinePipe,
    HelperPipes.GameNoticeVisibilityPipe,
    HelperPipes.GameTimelineFilterPipe,
    HelperPipes.GroupIdentifierFilterPipe,
    HelperPipes.PeriodFilterPipe,
    HelperPipes.ReversePeriodsPipe,
    HelperPipes.SortPlayersPipe,
    HelperPipes.SortTrikotnumbersPipe,
    HelperPipes.TeamLineupPlayerPipe,
    StartingPlayerPositionTitlePipe,
    CompletedAwardsFilterPipe,
    AwardTitlePipe,
    HasStartingPlayerPipe,
  ],
})
export class UikitCommonModule {}
